### ISSUE TITLE
Including license in NPM package

### ISSUE THREAD

**Issue by paulbarmstrong** [remarkablemark/inline-style-parser#124]
## Problem

While scanning my dependencies I found that the [inline-style-parser NPM package](https://www.npmjs.com/package/inline-style-parser) doesn't include a license. I saw from [the README](https://github.com/remarkablemark/inline-style-parser?tab=readme-ov-file#license) that this project uses an instance of the MIT license from another repo. Given that this license requires that it be included in all copies or substantial portions of the Software, I think it may make sense for the license to be included in the NPM package.

## Suggested Solution

I suggest adding the license as a file in this repo, and allowing that to be published to the NPM package. I think most NPM packages already include their license.

## Keywords

license

**Comment by remarkablemark** [comment]
@paulbarmstrong would you like to open a PR?

**Comment by paulbarmstrong** [comment]
I wouldn't mind opening a PR but I'm not quite sure how the license should be. Should it use the same license from reworkcss that gives copyright to TJ Holowaychuk?

**Comment by remarkablemark** [comment]
I opened a PR #125

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/inline-style-parser/pull/126#issuecomment-2019242715
